apiVersion: v1
kind: Namespace
metadata:
  name: dockerapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment
  namespace: dockerapp
spec:
  selector:
    matchLabels:
      app: docker-demo-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: docker-demo-k8s
    spec:
      containers:
        - name: user-app-container
          image: skumary200/spring-docker-cicd:1.0.0-4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8010

---
apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: dockerapp
spec:
  selector:
    app: docker-demo-k8s
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8010
  type: NodePort